#!/usr/bin/env python3
"""Render a Desk2Quant BRAG slim video about products and 1-on-1 sessions.

The screenshots and claims were checked on the public Desk2Quant site on
26 September 2026. All music and UI sounds are generated by this script.
"""

from __future__ import annotations

import math
import shutil
import subprocess
import wave
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[2]
ASSETS = Path(__file__).resolve().parent / "assets"
OUT = ROOT / "brag-output"
WORK = OUT / "work"
W, H, FPS, DURATION = 1280, 720, 30, 21
BG = (247, 248, 245)
INK = (12, 17, 19)
NAVY = (7, 23, 33)
TEAL = (67, 219, 184)
PINK = (245, 95, 130)
YELLOW = (255, 204, 73)
WHITE = (252, 252, 250)
MUTED = (102, 111, 114)
FONT_DIR = Path("/usr/share/fonts/truetype/dejavu")
FONT_BOLD = FONT_DIR / "DejaVuSans-Bold.ttf"
FONT_REG = FONT_DIR / "DejaVuSans.ttf"
FONT_MONO = FONT_DIR / "DejaVuSansMono.ttf"


def font(size: int, weight: str = "bold") -> ImageFont.FreeTypeFont:
    source = {"bold": FONT_BOLD, "regular": FONT_REG, "mono": FONT_MONO}[weight]
    return ImageFont.truetype(str(source), size)


def clamp(x: float) -> float:
    return max(0.0, min(1.0, x))


def ease(x: float) -> float:
    x = clamp(x)
    return x * x * (3 - 2 * x)


def text(draw: ImageDraw.ImageDraw, xy: tuple[int, int], value: str,
         size: int, color: tuple[int, int, int], weight: str = "bold",
         spacing: int = 1, anchor: str | None = None) -> None:
    draw.multiline_text(xy, value, font=font(size, weight), fill=color,
                        spacing=spacing, anchor=anchor)


def rounded(draw: ImageDraw.ImageDraw, box: tuple[int, int, int, int],
            fill: tuple[int, int, int], outline=None, width: int = 1,
            radius: int = 16) -> None:
    draw.rounded_rectangle(box, radius=radius, fill=fill, outline=outline,
                           width=width)


def mark(canvas: Image.Image, x: int, y: int, size: int) -> None:
    """Draw the official repository SVG's paths at output resolution."""
    scale = size / 64
    symbol = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(symbol)
    d.rounded_rectangle((3 * scale, 3 * scale, 61 * scale, 61 * scale),
                        radius=17 * scale, fill=(9, 9, 9))
    points = [(14, 44), (25.5, 33.5), (35.5, 37.5), (50, 21)]
    d.line([(a * scale, b * scale) for a, b in points], fill="white",
           width=max(2, round(4.5 * scale)), joint="curve")
    r = 3.5 * scale
    for a, b in points[:-1]:
        d.ellipse(((a * scale - r), (b * scale - r),
                   (a * scale + r), (b * scale + r)), fill="white")
    d.line([(42.5 * scale, 21 * scale), (50 * scale, 21 * scale),
            (50 * scale, 28.5 * scale)], fill="white",
           width=max(2, round(4.5 * scale)), joint="curve")
    canvas.paste(symbol, (x, y), symbol)


def paper(canvas: Image.Image) -> None:
    d = ImageDraw.Draw(canvas)
    d.rectangle((0, 0, W, H), fill=BG)
    for x in range(0, W, 40):
        d.line((x, 0, x, H), fill=(233, 236, 232), width=1)
    for y in range(0, H, 40):
        d.line((0, y, W, y), fill=(233, 236, 232), width=1)


def header(canvas: Image.Image, dark: bool = False) -> None:
    d = ImageDraw.Draw(canvas)
    fill = NAVY if dark else BG
    fg = WHITE if dark else INK
    d.rectangle((0, 0, W, 74), fill=fill)
    d.line((0, 73, W, 73), fill=(52, 73, 77) if dark else INK, width=2)
    mark(canvas, 45, 12, 50)
    text(d, (107, 25), "Desk2Quant", 24, fg)
    text(d, (940, 31), "D2Q / PRODUCTS + SESSIONS", 14, TEAL if dark else MUTED,
         weight="mono")


def image_card(canvas: Image.Image, photo: Image.Image,
               box: tuple[int, int, int, int], shadow: bool = True) -> None:
    x, y, w, h = box
    d = ImageDraw.Draw(canvas)
    if shadow:
        d.rectangle((x + 12, y + 12, x + w + 12, y + h + 12), fill=TEAL)
    d.rectangle((x - 2, y - 2, x + w + 2, y + h + 2), fill=INK)
    photo = photo.resize((w, h), Image.Resampling.LANCZOS)
    canvas.paste(photo, (x, y))


CATALOG_SHOT = Image.open(ASSETS / "products-catalog.jpg").convert("RGB")
BUNDLE_SHOT = Image.open(ASSETS / "complete-bundle.jpg").convert("RGB")
SESSION_SHOT = Image.open(ASSETS / "sessions.jpg").convert("RGB")
BOOKING_SHOT = Image.open(ASSETS / "booking.jpg").convert("RGB")
CATALOG_CARDS = CATALOG_SHOT.crop((357, 252, 977, 886))
BUNDLE_COVER = BUNDLE_SHOT.crop((160, 314, 492, 727))
SESSION_CARDS = SESSION_SHOT.crop((42, 122, 1292, 635))
BOOKING_FORM = BOOKING_SHOT.crop((706, 169, 1292, 730))


def label(draw: ImageDraw.ImageDraw, value: str, x: int, y: int,
          dark: bool = False) -> None:
    text(draw, (x, y), value, 17, TEAL if dark else MUTED, "mono")


def first_scene(canvas: Image.Image, local_t: float) -> None:
    paper(canvas)
    header(canvas)
    d = ImageDraw.Draw(canvas)
    slide = 1 - ease(local_t / .55)
    x = round(69 - 100 * slide)
    rounded(d, (x, 124, x + 523, 166), WHITE, outline=INK, width=2,
            radius=4)
    label(d, "PRACTITIONER-BUILT QUANT LEARNING", x + 16, 134)
    text(d, (x, 205), "QUANT PRODUCTS.", 54, INK)
    text(d, (x, 289), "1-ON-1 SESSIONS.", 48, INK)
    d.rectangle((x, 378, x + round(535 *
                 ease((local_t - .45) / .65)), 386), fill=TEAL)
    text(d, (x + 2, 430),
         "Notes, code and projects. Then focused\nfeedback from a practitioner.",
         23, MUTED, "regular", spacing=9)
    label(d, "PRICING  /  RISK  /  XVA  /  INTERVIEWS", x + 1, 633)

    cover_x = round(818 + 550 * (1 - ease((local_t - .12) / .65)))
    rounded(d, (cover_x + 14, 129, cover_x + 373, 585), TEAL,
            radius=5)
    image_card(canvas, BUNDLE_COVER, (cover_x, 115, 358, 456),
               shadow=False)
    d = ImageDraw.Draw(canvas)
    rounded(d, (cover_x + 2, 588, cover_x + 358, 617), NAVY,
            radius=2)
    text(d, (cover_x + 15, 594), "COMPLETE QUANT SYSTEM", 15,
         TEAL, "mono")


def second_scene(canvas: Image.Image, local_t: float) -> None:
    paper(canvas)
    header(canvas)
    d = ImageDraw.Draw(canvas)
    x = round(67 - 90 * (1 - ease(local_t / .5)))
    label(d, "// 01  DIGITAL PRODUCTS", x, 121)
    text(d, (x, 181), "PICK YOUR\nNEXT SKILL.", 53, INK,
         spacing=11)
    d.rectangle((x + 1, 380, x + 483, 387), fill=TEAL)
    for i, (number, title) in enumerate((
        ("45", "QUANT PROJECTS"),
        ("1000+", "INTERVIEW PROBLEMS"),
        ("PDF + CODE", "DESK-FOCUSED RESOURCES"),
    )):
        yy = 420 + i * 72
        rounded(d, (x, yy, x + 475, yy + 59), WHITE,
                outline=INK, width=2, radius=3)
        text(d, (x + 16, yy + 14), number, 20, INK, "mono")
        text(d, (x + 160, yy + 18), title, 15, MUTED, "mono")
    label(d, "ACTUAL DESK2QUANT CATALOG", x, 662)

    pic_x = round(631 + 680 * (1 - ease((local_t - .13) / .7)))
    image_card(canvas, CATALOG_CARDS, (pic_x, 116, 572, 560))
    d = ImageDraw.Draw(canvas)
    rounded(d, (pic_x + 21, 643, pic_x + 343, 677), NAVY, radius=2)
    text(d, (pic_x + 33, 650), "BROWSE INDIVIDUAL PRODUCTS", 14,
         TEAL, "mono")


def third_scene(canvas: Image.Image, local_t: float) -> None:
    d = ImageDraw.Draw(canvas)
    d.rectangle((0, 0, W, H), fill=NAVY)
    header(canvas, dark=True)
    x = round(65 - 90 * (1 - ease(local_t / .48)))
    label(d, "// THE COMPLETE SYSTEM", x, 119, dark=True)
    text(d, (x, 186), "FRONT OFFICE\n& RISK QUANT", 51,
         WHITE, spacing=12)
    text(d, (x, 363), "One structured professional bundle.", 23,
         (211, 225, 226), "regular")
    text(d, (x, 414), "Pricing · Models · Risk · XVA · Interviews",
         19, TEAL, "regular")
    for i, (n, what) in enumerate((("41+", "PDFS"),
                                   ("60+", "SCRIPTS"),
                                   ("1000+", "PROBLEMS"))):
        cx = x + i * 218
        rounded(d, (cx, 498, cx + 198, 594), (13, 43, 52),
                outline=(64, 129, 126), width=2, radius=3)
        text(d, (cx + 17, 511), n, 32, WHITE)
        text(d, (cx + 18, 556), what, 14, TEAL, "mono")
    label(d, "FROM FOUNDATIONS TO DEFENSIBLE DESK REASONING",
          x, 642, dark=True)

    pic_x = round(812 + 540 * (1 - ease((local_t - .1) / .62)))
    rounded(d, (pic_x + 13, 139, pic_x + 376, 598),
            (22, 107, 101), radius=5)
    image_card(canvas, BUNDLE_COVER, (pic_x, 126, 363, 449),
               shadow=False)


def fourth_scene(canvas: Image.Image, local_t: float) -> None:
    paper(canvas)
    header(canvas)
    d = ImageDraw.Draw(canvas)
    x = round(62 - 85 * (1 - ease(local_t / .5)))
    label(d, "// 02  PERSONAL MENTORSHIP", x, 113)
    text(d, (x, 149), "PERSONALIZED 1-ON-1 SESSIONS", 43, INK)
    text(d, (x + 2, 207),
         "Quant doubts. Resume review. Front office & risk prep.",
         20, MUTED, "regular")
    pic_y = round(244 + 510 * (1 - ease((local_t - .1) / .65)))
    image_card(canvas, SESSION_CARDS, (49, pic_y, 1181, 455))
    d = ImageDraw.Draw(canvas)
    rounded(d, (67, 663, 552, 700), NAVY, radius=3)
    text(d, (82, 672), "REAL SESSIONS  /  15 · 30 · 45 MIN",
         16, TEAL, "mono")


def fifth_scene(canvas: Image.Image, local_t: float) -> None:
    d = ImageDraw.Draw(canvas)
    d.rectangle((0, 0, W, H), fill=NAVY)
    header(canvas, dark=True)
    x = round(65 - 95 * (1 - ease(local_t / .5)))
    label(d, "// YOUR NEXT STEP", x, 132, dark=True)
    text(d, (x, 205), "BROWSE\nPRODUCTS.", 49, WHITE, spacing=10)
    text(d, (x, 354), "BOOK A\nSESSION.", 49, TEAL, spacing=10)
    d.rectangle((x + 1, 509, x + 1 + round(464 * ease((local_t - .5) / .6)),
                 518), fill=TEAL)
    text(d, (x, 551), "desk2quant.com", 33, WHITE)
    label(d, "LEARN IT. IMPLEMENT IT. DEFEND IT.", x, 637, dark=True)

    pic_x = round(672 + 640 * (1 - ease((local_t - .13) / .65)))
    image_card(canvas, BOOKING_FORM, (pic_x, 121, 545, 522))
    d = ImageDraw.Draw(canvas)
    rounded(d, (pic_x + 4, 605, pic_x + 541, 644), TEAL,
            radius=2)
    text(d, (pic_x + 22, 615), "SELECT A SESSION  →  CHOOSE A TIME",
         17, INK, "mono")


def frame_at(seconds: float) -> Image.Image:
    canvas = Image.new("RGB", (W, H), BG)
    if seconds < 3.4:
        first_scene(canvas, seconds)
    elif seconds < 8.0:
        second_scene(canvas, seconds - 3.4)
    elif seconds < 12.4:
        third_scene(canvas, seconds - 8.0)
    elif seconds < 17.2:
        fourth_scene(canvas, seconds - 12.4)
    else:
        fifth_scene(canvas, seconds - 17.2)
    return canvas


def make_audio(path: Path) -> None:
    rate = 44100
    length = DURATION * rate
    sound = np.zeros(length, dtype=np.float64)
    rng = np.random.default_rng(20260926)
    beat = 60 / 108
    chords = [(220, 261.63, 329.63), (174.61, 220, 261.63),
              (196, 261.63, 329.63), (196, 246.94, 293.66)]

    for bar in range(10):
        start = int(bar * 4 * beat * rate)
        if start >= length:
            break
        n = min(int(2.45 * rate), length - start)
        t = np.arange(n) / rate
        chord = chords[bar % 4]
        swell = np.minimum(t / .35, 1) * np.minimum((2.45 - t) / .55, 1)
        pad = sum(np.sin(2 * np.pi * f * t) +
                  .12 * np.sin(2 * np.pi * (f * 2.001) * t)
                  for f in chord) / 3
        sound[start:start+n] += .045 * pad * np.maximum(0, swell)
        bass = np.sin(2 * np.pi * (chord[0] / 2) * t)
        sound[start:start+n] += .042 * bass * np.exp(-t * 1.25)

    for k in range(math.ceil(DURATION / beat)):
        start = int(k * beat * rate)
        n = min(int(.22 * rate), length - start)
        if n <= 0:
            break
        t = np.arange(n) / rate
        phase = 2 * np.pi * (63 * t + 75 * (.05 / 4.5) *
                            (1 - np.exp(-t * 4.5)))
        sound[start:start+n] += .115 * np.sin(phase) * np.exp(-t * 19)
        if k % 2:
            noise = rng.standard_normal(n)
            high = np.r_[noise[0], np.diff(noise)]
            sound[start:start+n] += .014 * high * np.exp(-t * 45)
        else:
            sound[start:start+n] += .007 * np.sin(2 * np.pi * 1100 * t) * \
                np.exp(-t * 90)

    for scene_t in [0, 3.4, 8, 12.4, 17.2]:
        start = int(scene_t * rate)
        n = min(int(.28 * rate), length - start)
        t = np.arange(n) / rate
        tone = (np.sin(2 * np.pi * 440 * t) +
                .45 * np.sin(2 * np.pi * 660 * t))
        sound[start:start+n] += .031 * tone * np.exp(-t * 16)

    ramp = np.minimum(np.arange(length) / (.32 * rate), 1)
    fade = np.minimum((length - np.arange(length)) / (.9 * rate), 1)
    sound = np.tanh(sound * 1.8) * .72 * np.maximum(0, ramp) * \
        np.maximum(0, fade)
    pcm = np.clip(sound * 32767, -32768, 32767).astype("<i2")
    with wave.open(str(path), "wb") as wav:
        wav.setnchannels(1)
        wav.setsampwidth(2)
        wav.setframerate(rate)
        wav.writeframes(pcm.tobytes())


def run() -> None:
    if not shutil.which("ffmpeg"):
        raise RuntimeError("FFmpeg is required on PATH")
    WORK.mkdir(parents=True, exist_ok=True)
    # The poster and first frame say exactly what the video promotes.
    poster = frame_at(1.8)
    poster.save(OUT / "brag.jpg", quality=93, subsampling=0)
    make_audio(WORK / "original-soundtrack.wav")
    temp_video = WORK / "silent.mp4"
    command = ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
               "-f", "rawvideo", "-pixel_format", "rgb24", "-video_size",
               f"{W}x{H}", "-framerate", str(FPS), "-i", "-",
               "-c:v", "libx264", "-preset", "fast", "-crf", "20",
               "-pix_fmt", "yuv420p", "-movflags", "+faststart",
               str(temp_video)]
    proc = subprocess.Popen(command, stdin=subprocess.PIPE)
    assert proc.stdin is not None
    try:
        for i in range(FPS * DURATION):
            frame = poster if i == 0 else frame_at(i / FPS)
            proc.stdin.write(frame.tobytes())
        proc.stdin.close()
    except BrokenPipeError as exc:
        raise RuntimeError("FFmpeg stopped during rendering") from exc
    if proc.wait():
        raise RuntimeError("Video encoding failed")
    subprocess.run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
                    "-i", str(temp_video), "-i",
                    str(WORK / "original-soundtrack.wav"), "-c:v", "copy",
                    "-c:a", "aac", "-b:a", "160k", "-af",
                    "loudnorm=I=-20:TP=-1.5:LRA=11", "-shortest",
                    "-movflags", "+faststart", str(OUT / "brag.mp4")],
                   check=True)
    for name in ("storyboard.md", "caption.txt"):
        (OUT / name).write_text((Path(__file__).parent / name).read_text())
    print(f"Created {OUT / 'brag.mp4'} and {OUT / 'brag.jpg'}")


if __name__ == "__main__":
    run()
