#!/usr/bin/env python3
"""Render the first Desk2Quant BRAG slim video from public product material.

The screenshots and copy are from the actual Desk2Quant Desk Simulator. The
incident is a fictional teaching case; the score/result is never presented as
real bank data. All music and UI sounds are generated by this script.
"""

from __future__ import annotations

import math
import shutil
import subprocess
import wave
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[2]
ASSETS = Path(__file__).resolve().parent / "assets"
OUT = ROOT / "brag-output"
WORK = OUT / "work"
W, H, FPS, DURATION = 1280, 720, 30, 21
BG = (247, 248, 245)
INK = (12, 17, 19)
NAVY = (7, 23, 33)
TEAL = (67, 219, 184)
PINK = (245, 95, 130)
YELLOW = (255, 204, 73)
WHITE = (252, 252, 250)
MUTED = (102, 111, 114)
FONT_DIR = Path("/usr/share/fonts/truetype/dejavu")
FONT_BOLD = FONT_DIR / "DejaVuSans-Bold.ttf"
FONT_REG = FONT_DIR / "DejaVuSans.ttf"
FONT_MONO = FONT_DIR / "DejaVuSansMono.ttf"


def font(size: int, weight: str = "bold") -> ImageFont.FreeTypeFont:
    source = {"bold": FONT_BOLD, "regular": FONT_REG, "mono": FONT_MONO}[weight]
    return ImageFont.truetype(str(source), size)


def clamp(x: float) -> float:
    return max(0.0, min(1.0, x))


def ease(x: float) -> float:
    x = clamp(x)
    return x * x * (3 - 2 * x)


def text(draw: ImageDraw.ImageDraw, xy: tuple[int, int], value: str,
         size: int, color: tuple[int, int, int], weight: str = "bold",
         spacing: int = 1, anchor: str | None = None) -> None:
    draw.multiline_text(xy, value, font=font(size, weight), fill=color,
                        spacing=spacing, anchor=anchor)


def rounded(draw: ImageDraw.ImageDraw, box: tuple[int, int, int, int],
            fill: tuple[int, int, int], outline=None, width: int = 1,
            radius: int = 16) -> None:
    draw.rounded_rectangle(box, radius=radius, fill=fill, outline=outline,
                           width=width)


def mark(canvas: Image.Image, x: int, y: int, size: int) -> None:
    """Draw the official repository SVG's paths at output resolution."""
    scale = size / 64
    symbol = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(symbol)
    d.rounded_rectangle((3 * scale, 3 * scale, 61 * scale, 61 * scale),
                        radius=17 * scale, fill=(9, 9, 9))
    points = [(14, 44), (25.5, 33.5), (35.5, 37.5), (50, 21)]
    d.line([(a * scale, b * scale) for a, b in points], fill="white",
           width=max(2, round(4.5 * scale)), joint="curve")
    r = 3.5 * scale
    for a, b in points[:-1]:
        d.ellipse(((a * scale - r), (b * scale - r),
                   (a * scale + r), (b * scale + r)), fill="white")
    d.line([(42.5 * scale, 21 * scale), (50 * scale, 21 * scale),
            (50 * scale, 28.5 * scale)], fill="white",
           width=max(2, round(4.5 * scale)), joint="curve")
    canvas.paste(symbol, (x, y), symbol)


def paper(canvas: Image.Image) -> None:
    d = ImageDraw.Draw(canvas)
    d.rectangle((0, 0, W, H), fill=BG)
    for x in range(0, W, 40):
        d.line((x, 0, x, H), fill=(233, 236, 232), width=1)
    for y in range(0, H, 40):
        d.line((0, y, W, y), fill=(233, 236, 232), width=1)


def header(canvas: Image.Image, dark: bool = False) -> None:
    d = ImageDraw.Draw(canvas)
    fill = NAVY if dark else BG
    fg = WHITE if dark else INK
    d.rectangle((0, 0, W, 74), fill=fill)
    d.line((0, 73, W, 73), fill=(52, 73, 77) if dark else INK, width=2)
    mark(canvas, 45, 12, 50)
    text(d, (107, 25), "Desk2Quant", 24, fg)
    text(d, (1138, 31), "D2Q // 01", 14, TEAL if dark else MUTED,
         weight="mono")


def image_card(canvas: Image.Image, photo: Image.Image,
               box: tuple[int, int, int, int], shadow: bool = True) -> None:
    x, y, w, h = box
    d = ImageDraw.Draw(canvas)
    if shadow:
        d.rectangle((x + 12, y + 12, x + w + 12, y + h + 12), fill=TEAL)
    d.rectangle((x - 2, y - 2, x + w + 2, y + h + 2), fill=INK)
    photo = photo.resize((w, h), Image.Resampling.LANCZOS)
    canvas.paste(photo, (x, y))


SIM_SHOT = Image.open(ASSETS / "simulator.jpg").convert("RGB")
INCIDENT_SHOT = Image.open(ASSETS / "incident-brief.jpg").convert("RGB")
SIM_PANEL = SIM_SHOT.crop((640, 205, 1302, 702))
INCIDENT_CENTER = INCIDENT_SHOT.crop((248, 89, 1036, 892))


def first_scene(canvas: Image.Image, local_t: float) -> None:
    paper(canvas)
    header(canvas)
    d = ImageDraw.Draw(canvas)
    enter = ease(local_t / .48)
    x = round(67 - (1 - enter) * 110)
    text(d, (x, 117), "// SIMULATED DESK INCIDENT", 20, MUTED, "mono")
    text(d, (x, 185), "THE NUMBERS", 67, INK)
    text(d, (x, 274), "DON'T MATCH.", 67, INK)
    d.rectangle((x + 1, 378,
                 x + 1 + round(530 * ease((local_t - .7) / .55)), 387),
                fill=TEAL)
    text(d, (x + 2, 444), "What would you test first?", 26, MUTED, "regular")
    text(d, (x + 2, 610), "EQUITY DERIVATIVES  /  P&L CONTROL", 17, MUTED,
         "mono")

    slide = 1 - ease((local_t - .13) / .64)
    right = round(1180 + 360 * slide)
    left = right - 430
    rounded(d, (left + 10, 125 + 10, right + 10, 605 + 10), TEAL, radius=5)
    rounded(d, (left, 125, right, 605), NAVY, outline=INK, width=3, radius=5)
    text(d, (left + 34, 157), "INCIDENT 01 / THE MISSING VEGA", 16,
         TEAL, "mono")
    d.line((left + 34, 198, right - 34, 198), fill=(62, 82, 86), width=2)
    numbers = [
        ("DESK ESTIMATE", "+$1.42m", WHITE),
        ("OFFICIAL P&L", "+$0.61m", WHITE),
        ("UNEXPLAINED", "−$0.81m", PINK),
    ]
    for i, (label, value, col) in enumerate(numbers):
        yy = 220 + i * 119
        a = ease((local_t - .52 - i * .17) / .4)
        if a > 0:
            text(d, (left + 36, yy), label, 16, TEAL, "mono")
            # Reveal the figure as the right-hand side of a masked scan.
            text(d, (left + 36, yy + 27), value, 43, col)
            cover_start = left + 36 + round(355 * a)
            if cover_start < right - 25:
                d.rectangle((cover_start, yy + 28, right - 26, yy + 86),
                            fill=NAVY)
        if i < 2:
            d.line((left + 35, yy + 106, right - 35, yy + 106),
                   fill=(58, 76, 80), width=1)


def second_scene(canvas: Image.Image, local_t: float) -> None:
    paper(canvas)
    header(canvas)
    d = ImageDraw.Draw(canvas)
    text(d, (65, 123), "// FREE DESK SIMULATOR", 19, MUTED, "mono")
    x = round(66 - 80 * (1 - ease(local_t / .54)))
    text(d, (x, 177), "YOUR FIRST DAY\nON THE QUANT\nDESK.", 53, INK,
         spacing=14)
    rounded(d, (65, 492, 524, 549), WHITE, outline=INK, width=2, radius=5)
    text(d, (84, 510), "OPEN THE FIRST INCIDENT  →", 20, INK, "mono")
    text(d, (67, 605), "REALISTIC INCIDENTS  •  FREE PRACTICE", 17, MUTED,
         "mono")
    appear = ease((local_t - .23) / .72)
    pic_x = round(570 + 700 * (1 - appear))
    image_card(canvas, SIM_PANEL, (pic_x, 132, 622, 467))
    if local_t > 1.4:
        w = round(570 * ease((local_t - 1.4) / 1.1))
        d = ImageDraw.Draw(canvas)
        d.line((pic_x + 26, 572, pic_x + 26 + w, 572), fill=TEAL, width=5)


def third_scene(canvas: Image.Image, local_t: float) -> None:
    d = ImageDraw.Draw(canvas)
    d.rectangle((0, 0, W, H), fill=NAVY)
    header(canvas, dark=True)
    x = round(58 - 80 * (1 - ease(local_t / .44)))
    text(d, (x, 129), "// THE MISSING VEGA", 19, TEAL, "mono")
    text(d, (x, 193), "READ THE\nBRIEF.", 47, WHITE, spacing=10)
    text(d, (x, 353), "FOLLOW THE\nEVIDENCE.", 43, TEAL, spacing=9)
    text(d, (x, 536), "A real investigation flow\ninside the free simulator.",
         24, (200, 210, 212), "regular", spacing=12)
    img_y = round(106 + 630 * (1 - ease((local_t - .1) / .7)))
    image_card(canvas, INCIDENT_CENTER, (497, img_y, 717, 730), shadow=False)
    d = ImageDraw.Draw(canvas)
    d.rounded_rectangle((491, 100, 1222, 705), radius=3,
                        outline=TEAL, width=3)
    # Keep the source screenshot intact; the moving focus is outside its crop.
    for index, label in enumerate(("01 BRIEF", "02 EVIDENCE", "03 TESTS")):
        if local_t > 1.25 + index * .65:
            col = TEAL if index == min(2, int((local_t - 1.25) / .65)) else WHITE
            text(d, (x + index * 143, 662), label, 14, col, "mono")


def fourth_scene(canvas: Image.Image, local_t: float) -> None:
    d = ImageDraw.Draw(canvas)
    d.rectangle((0, 0, W, H), fill=NAVY)
    header(canvas, dark=True)
    text(d, (58, 139), "// INVESTIGATION QUEUE", 18, TEAL, "mono")
    text(d, (58, 222), "RUN A\nCONTROLLED\nTEST.", 48, WHITE, spacing=10)
    text(d, (60, 568), "One decisive test beats\nmore noisy output.",
         21, (187, 201, 203), "regular", spacing=9)
    enter = ease((local_t - .15) / .6)
    panel_x = round(453 + 660 * (1 - enter))
    rounded(d, (panel_x + 9, 135 + 9, panel_x + 752 + 9, 616 + 9),
            (9, 93, 83), radius=5)
    rounded(d, (panel_x, 135, panel_x + 752, 616), (11, 35, 46),
            outline=TEAL, width=2, radius=5)
    text(d, (panel_x + 28, 163), "MARKET DATA  /  SPX 3M ATM", 19,
         TEAL, "mono")
    d.line((panel_x + 28, 205, panel_x + 720, 205), fill=(65, 92, 96), width=1)
    text(d, (panel_x + 28, 238), "COMPARE VOLATILITY SNAPSHOTS", 26,
         WHITE)
    if local_t > 1.05:
        d.line((panel_x + 28, 290, panel_x + 28 +
                round(670 * ease((local_t - 1.05) / .65)), 290),
               fill=TEAL, width=4)
    text(d, (panel_x + 34, 329), "RISK COPY", 16, (178, 202, 204), "mono")
    text(d, (panel_x + 407, 329), "FRONT OFFICE", 16,
         (178, 202, 204), "mono")
    if local_t > 1.25:
        text(d, (panel_x + 34, 362), "18.10%", 49, WHITE)
    if local_t > 1.75:
        text(d, (panel_x + 407, 362), "20.50%", 49, TEAL)
    if local_t > 2.25:
        rounded(d, (panel_x + 27, 458, panel_x + 725, 552),
                (15, 63, 65), outline=TEAL, width=1, radius=4)
        text(d, (panel_x + 44, 474), "MISMATCH ISOLATED", 16, TEAL, "mono")
        text(d, (panel_x + 44, 502), "SPX 3M ATM", 28, WHITE)
    text(d, (panel_x + 554, 576), "BUDGET 100 → 90", 15, TEAL, "mono")


def fifth_scene(canvas: Image.Image, local_t: float) -> None:
    paper(canvas)
    d = ImageDraw.Draw(canvas)
    mark(canvas, 84, 105, 88)
    text(d, (195, 132), "Desk2Quant", 43, INK)
    d.line((85, 228, 1196, 228), fill=INK, width=3)
    p = ease(local_t / .55)
    x = round(85 - 110 * (1 - p))
    text(d, (x, 268), "INTERVIEW READY.", 63, INK)
    text(d, (x, 367), "DESK READY.", 63, INK)
    d.rectangle((x, 453, x + round(635 * ease((local_t - .6) / .65)), 464),
                fill=TEAL)
    rounded(d, (84, 521, 1195, 631), NAVY, outline=INK, width=2, radius=5)
    text(d, (115, 547), "desk2quant.com", 39, WHITE)
    text(d, (715, 563), "SIMULATOR · RESOURCES · MENTORSHIP", 17,
         TEAL, "mono")
    text(d, (87, 666), "PRICING  /  RISK  /  MODEL VALIDATION  /  INTERVIEWS",
         16, MUTED, "mono")


def frame_at(seconds: float) -> Image.Image:
    canvas = Image.new("RGB", (W, H), BG)
    if seconds < 3.6:
        first_scene(canvas, seconds)
    elif seconds < 8:
        second_scene(canvas, seconds - 3.6)
    elif seconds < 12.7:
        third_scene(canvas, seconds - 8)
    elif seconds < 17.2:
        fourth_scene(canvas, seconds - 12.7)
    else:
        fifth_scene(canvas, seconds - 17.2)
    return canvas


def make_audio(path: Path) -> None:
    rate = 44100
    length = DURATION * rate
    sound = np.zeros(length, dtype=np.float64)
    rng = np.random.default_rng(20260926)
    beat = 60 / 108
    chords = [(220, 261.63, 329.63), (174.61, 220, 261.63),
              (196, 261.63, 329.63), (196, 246.94, 293.66)]

    for bar in range(10):
        start = int(bar * 4 * beat * rate)
        if start >= length:
            break
        n = min(int(2.45 * rate), length - start)
        t = np.arange(n) / rate
        chord = chords[bar % 4]
        swell = np.minimum(t / .35, 1) * np.minimum((2.45 - t) / .55, 1)
        pad = sum(np.sin(2 * np.pi * f * t) +
                  .12 * np.sin(2 * np.pi * (f * 2.001) * t)
                  for f in chord) / 3
        sound[start:start+n] += .045 * pad * np.maximum(0, swell)
        bass = np.sin(2 * np.pi * (chord[0] / 2) * t)
        sound[start:start+n] += .042 * bass * np.exp(-t * 1.25)

    for k in range(math.ceil(DURATION / beat)):
        start = int(k * beat * rate)
        n = min(int(.22 * rate), length - start)
        if n <= 0:
            break
        t = np.arange(n) / rate
        phase = 2 * np.pi * (63 * t + 75 * (.05 / 4.5) *
                            (1 - np.exp(-t * 4.5)))
        sound[start:start+n] += .115 * np.sin(phase) * np.exp(-t * 19)
        if k % 2:
            noise = rng.standard_normal(n)
            high = np.r_[noise[0], np.diff(noise)]
            sound[start:start+n] += .014 * high * np.exp(-t * 45)
        else:
            sound[start:start+n] += .007 * np.sin(2 * np.pi * 1100 * t) * \
                np.exp(-t * 90)

    for scene_t in [0, 3.6, 8, 12.7, 17.2]:
        start = int(scene_t * rate)
        n = min(int(.28 * rate), length - start)
        t = np.arange(n) / rate
        tone = (np.sin(2 * np.pi * 440 * t) +
                .45 * np.sin(2 * np.pi * 660 * t))
        sound[start:start+n] += .031 * tone * np.exp(-t * 16)

    ramp = np.minimum(np.arange(length) / (.32 * rate), 1)
    fade = np.minimum((length - np.arange(length)) / (.9 * rate), 1)
    sound = np.tanh(sound * 1.8) * .72 * np.maximum(0, ramp) * \
        np.maximum(0, fade)
    pcm = np.clip(sound * 32767, -32768, 32767).astype("<i2")
    with wave.open(str(path), "wb") as wav:
        wav.setnchannels(1)
        wav.setsampwidth(2)
        wav.setframerate(rate)
        wav.writeframes(pcm.tobytes())


def run() -> None:
    if not shutil.which("ffmpeg"):
        raise RuntimeError("FFmpeg is required on PATH")
    WORK.mkdir(parents=True, exist_ok=True)
    # A settled real-product frame is both the poster and the first video frame.
    poster = frame_at(6.3)
    poster.save(OUT / "brag.jpg", quality=93, subsampling=0)
    make_audio(WORK / "original-soundtrack.wav")
    temp_video = WORK / "silent.mp4"
    command = ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
               "-f", "rawvideo", "-pixel_format", "rgb24", "-video_size",
               f"{W}x{H}", "-framerate", str(FPS), "-i", "-",
               "-c:v", "libx264", "-preset", "fast", "-crf", "20",
               "-pix_fmt", "yuv420p", "-movflags", "+faststart",
               str(temp_video)]
    proc = subprocess.Popen(command, stdin=subprocess.PIPE)
    assert proc.stdin is not None
    try:
        for i in range(FPS * DURATION):
            frame = poster if i == 0 else frame_at(i / FPS)
            proc.stdin.write(frame.tobytes())
        proc.stdin.close()
    except BrokenPipeError as exc:
        raise RuntimeError("FFmpeg stopped during rendering") from exc
    if proc.wait():
        raise RuntimeError("Video encoding failed")
    subprocess.run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
                    "-i", str(temp_video), "-i",
                    str(WORK / "original-soundtrack.wav"), "-c:v", "copy",
                    "-c:a", "aac", "-b:a", "160k", "-af",
                    "loudnorm=I=-20:TP=-1.5:LRA=11", "-shortest",
                    "-movflags", "+faststart", str(OUT / "brag.mp4")],
                   check=True)
    print(f"Created {OUT / 'brag.mp4'} and {OUT / 'brag.jpg'}")


if __name__ == "__main__":
    run()
